# Generated by Django 6.0.1 on 2026-02-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fingerprint_credential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date'], 'verbose_name': 'Holiday', 'verbose_name_plural': 'Holidays'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='parent_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_branches', to='users.branch', verbose_name='Parent Branch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='users.branch', verbose_name='Branch (Optional)'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(unique=True, verbose_name='Holiday Date'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
