# Generated by Django 6.0.1 on 2026-02-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_branch_options_alter_customuser_options_and_more'),
        ('users', '0004_scanner_fingerprint_template'),
    ]

    operations = [
    ]
