# Generated by Django 6.0.2 on 2026-02-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_middle_name_customuser_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('employee', 'Ishchi'), ('director', 'Direktor')], default='employee', max_length=20),
        ),
    ]
