# Generated by Django 5.2.11 on 2026-03-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_branch_parent_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='signature_image',
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.TextField(default='', verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
