# Generated by Django 5.2.11 on 2026-03-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_signature_image_branch_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone',
        ),
    ]
