# Generated by Django 6.0.2 on 2026-03-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_signature_image_branch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='JSHSHIR (PINFL)'),
        ),
    ]
