# Generated by Django 6.0.2 on 2026-03-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_pinfl'),
        ('users', '0010_remove_branch_address_remove_branch_phone'),
    ]

    operations = [
    ]
