# Generated by Django 6.0.1 on 2026-01-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('internal', 'I/CH - Ichki hujjat'), ('external', 'SH/T - Shartnoma/Tashqi hujjat')], max_length=50, verbose_name='Hujjat turi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Hujjat turi',
                'verbose_name_plural': 'Hujjat turlari',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('signature_request', "Imzo so'rovi"), ('document_signed', 'Hujjat imzolandi'), ('status_changed', "Holat o'zgardi")], max_length=30)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Buyruq nomi/sarlavhasi')),
                ('number', models.CharField(help_text='Masalan: 01-2025, BR-145/26 va h.k.', max_length=50, unique=True, verbose_name='Buyruq raqami')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Imzolash kutilmoqda'), ('partial', 'Qisman imzolangan'), ('completed', 'To‘liq imzolangan'), ('rejected', 'Rad etilgan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holati')),
                ('content', models.TextField(blank=True, verbose_name='Buyruq matni / mazmuni')),
                ('file', models.FileField(blank=True, null=True, upload_to='orders/files/%Y/%m/', verbose_name='Ilova qilingan fayl (PDF va boshq.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqti')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Imzolash muddati')),
                ('signature_type', models.CharField(choices=[('sequential', 'Ketma-ket'), ('parallel', 'Parallel')], default='sequential', max_length=20)),
            ],
            options={
                'verbose_name': 'Buyruq',
                'verbose_name_plural': 'Buyruqlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(verbose_name='Imzo tartibi')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='order_signatures/%Y/%m/%d/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/%Y/%m/%d/')),
                ('signed', models.BooleanField(default=False, verbose_name='Imzolandi')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Imzolangan vaqt')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buyruq imzo',
                'verbose_name_plural': 'Buyruq imzolar',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(default=1, help_text='1 - birinchi imzolashi kerak, 2 - ikkinchi va h.k.', verbose_name='Imzolash tartib raqami')),
                ('required', models.BooleanField(default=True, verbose_name='Majburiy imzo')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Izoh / lavozim')),
            ],
            options={
                'verbose_name': 'Imzolovchi',
                'verbose_name_plural': 'Imzolovchilar',
                'ordering': ['order_number'],
            },
        ),
    ]
