# Generated by Django 6.0.1 on 2026-01-22 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='users.branch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan xodim'),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='documents.order'),
        ),
        migrations.AddField(
            model_name='ordersignature',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.order'),
        ),
        migrations.AddField(
            model_name='ordersignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersigner',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='documents.order', verbose_name='Buyruq'),
        ),
        migrations.AddField(
            model_name='ordersigner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_to_sign', to=settings.AUTH_USER_MODEL, verbose_name='Imzolovchi'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together={('name', 'branch')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='documents_o_status_14fdff_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by'], name='documents_o_created_b6e682_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordersignature',
            unique_together={('order', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='ordersigner',
            unique_together={('order', 'user')},
        ),
    ]
