# Generated by Django 6.0.1 on 2026-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_type',
            field=models.CharField(choices=[('internal', 'Buyruq I/CH - Ichki hujjat'), ('external', 'Buyruq SH/T - Shartnoma/Tashqi hujjat'), ('official', 'Buyruq')], default='internal', max_length=20, verbose_name='Turi'),
        ),
    ]
