# Generated by Django 6.0.2 on 2026-02-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_order_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='director_approved',
            field=models.BooleanField(default=False, verbose_name='Direktor tasdiqladi'),
        ),
        migrations.AddField(
            model_name='order',
            name='director_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Direktor tasdiqlagan vaqt'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='orders/final_qr/%Y/%m/', verbose_name='Umumiy QR kod'),
        ),
    ]
