# Generated by Django 6.0.2 on 2026-02-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_order_director_approved_order_director_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stamped_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/stamped/%Y/%m/', verbose_name='Pechatli PDF'),
        ),
    ]
