# Generated by Django 5.2.11 on 2026-03-02 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_order_stamped_file'),
        ('users', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='document_type',
            field=models.CharField(choices=[('internal', 'Buyruq I/CH - Ichki hujjat'), ('external', 'Buyruq SH/T - Shartnoma/Tashqi hujjat'), ('official', 'Buyruq'), ('application', 'Ariza')], default='internal', max_length=20, verbose_name='Turi'),
        ),
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hujjat nomi')),
                ('file', models.FileField(upload_to='additional_docs/%Y/%m/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='users.branch', verbose_name='Filial')),
            ],
            options={
                'verbose_name': "Qo'shimcha hujjat",
                'verbose_name_plural': "Qo'shimcha hujjatlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='additional_docs',
            field=models.ManyToManyField(blank=True, related_name='orders', to='documents.additionaldocument', verbose_name="Qo'shimcha hujjatlar"),
        ),
    ]
