# Generated by Django 5.2.11 on 2026-03-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_order_document_type_additionaldocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='additional_docs/%Y/%m/', verbose_name='Fayl'),
        ),
    ]
