# Generated by Django 5.2.11 on 2026-03-03 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_additionaldocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldocument',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='Imzolandi'),
        ),
        migrations.AddField(
            model_name='additionaldocument',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='additional_docs/qr/%Y/%m/', verbose_name='QR kod'),
        ),
        migrations.AddField(
            model_name='additionaldocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Imzolangan vaqt'),
        ),
        migrations.AddField(
            model_name='additionaldocument',
            name='signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_docs_to_sign', to=settings.AUTH_USER_MODEL, verbose_name='Imzolovchi xodim'),
        ),
        migrations.AddField(
            model_name='additionaldocument',
            name='stamped_file',
            field=models.FileField(blank=True, null=True, upload_to='additional_docs/stamped/%Y/%m/', verbose_name='Pechatli PDF'),
        ),
    ]
