# Generated by Django 5.2.11 on 2026-03-06 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_additionaldocument_is_signed_and_more'),
        ('users', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hujjat nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_templates', to='users.branch', verbose_name='Filial (Ixtiyoriy)')),
            ],
            options={
                'verbose_name': "Qo'shimcha hujjat shabloni",
                'verbose_name_plural': "Qo'shimcha hujjat shablonlari",
                'ordering': ['name'],
            },
        ),
    ]
