# Generated by Django 5.2.11 on 2026-03-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_additionaldocumenttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ordersignature',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='ordersigner',
            name='comment',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
