# Generated by Django 5.2.11 on 2026-03-11 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_remove_order_content_remove_ordersignature_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqti'),
        ),
    ]
