# Generated by Django 5.2.11 on 2026-03-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_order_created_at'),
        ('users', '0009_remove_customuser_signature_image_branch_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(help_text='Masalan: 01-2025, BR-145/26 va h.k.', max_length=50, verbose_name='Buyruq raqami'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('number', 'branch')},
        ),
    ]
