# Generated by Django 5.2.11 on 2026-03-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_order_number_alter_order_unique_together'),
        ('users', '0011_merge_20260316_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='document_type',
            field=models.CharField(choices=[('internal', 'Buyruq I/CH - Ichki hujjat'), ('external', 'Buyruq SH/T - Shartnoma/Tashqi hujjat'), ('application', 'Ariza')], default='internal', max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('number', 'branch', 'document_type')},
        ),
    ]
