# Generated by Django 5.2.11 on 2026-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_order_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='additional_docs/%Y/%m/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='additionaldocument',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='additional_docs/qr/%Y/%m/', verbose_name='QR kod'),
        ),
        migrations.AlterField(
            model_name='additionaldocument',
            name='stamped_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='additional_docs/stamped/%Y/%m/', verbose_name='Pechatli PDF'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='orders/files/%Y/%m/', verbose_name='Ilova qilingan fayl (PDF va boshq.)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_qr_code',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='orders/final_qr/%Y/%m/', verbose_name='Umumiy QR kod'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stamped_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='orders/stamped/%Y/%m/', verbose_name='Pechatli PDF'),
        ),
        migrations.AlterField(
            model_name='ordersignature',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='qr_codes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ordersignature',
            name='signature_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='order_signatures/%Y/%m/%d/'),
        ),
    ]
